name: Flutter Build Apk
# This workflow is triggered on pushes to the repository on branch main.

on:
  push:
    branches:
    - main
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter with cache
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-
    
      - name: Download Flutter packages
        run: flutter pub get
    
    # Build apk.
      - name: Build Flutter apk file
      - run: flutter build apk
    
    # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          overwrite: true
          path: build/app/outputs/apk/release/ui_ux_designs.apk
